export enum ProductSubcategoryEnum {
  WRENCH = 'WRENCH',
  SCREWDRIVER = 'SCREWDRIVER',
  HAMMER = 'HAMMER',
  VOLTIMETER = 'VOLTIMETER',
  SCANNER = 'SCANNER',
  BOTTLE_JACK = 'BOTTLE_JACK',
  TROLLEY_JACK = 'TROLLEY_JACK',
  SCISSOR_JACK = 'SCISSOR_JACK',
}
