export enum ProductSubcategoryEnum {
  // HAND_TOOLS
  WRENCH = 'WRENCH',
  SCREWDRIVER = 'SCREWDRIVER',
  HAMMER = 'HAMMER',

  // DIAGNOSTIC_TOOLS
  VOLTIMETER = 'VOLTIMETER',
  SCANNER = 'SCANNER',

  // LIFTING_TOOLS
  BOTTLE_JACK = 'BOTTLE_JACK',
  TROLLEY_JACK = 'TROLLEY_JACK',
  SCISSOR_JACK = 'SCISSOR_JACK',
}
